db:
  org: "local"
  name: "db0"
  url: "http://localhost:8086"
  token: "RDV6dIFHQzEKx1Hb5m30xZ0trij_4nqjTg8SjDPHYw3ZWzkQmG0Tr55GObX2m3mA_K7Qg2-CUsx0j3hot_9HgQ=="
  stock_prices_table: "stock_price"

POSTGRES_HOST: localhost
POSTGRES_USER: postgres
POSTGRES_DB: postgres
POSTGRES_PASSWORD: 1234
POSTGRES_PORT: 5432
